### ISSUE TITLE
Invalid Relationship File

### ISSUE THREAD

**Issue by blendimc** [jfryman/puppet-nginx#299]
Server is a pretty plain vanilla Ubuntu 12.04 install just setup today.

Here is the Vhost config file I have setup (domain names have been changed to protect the innocent). 

    node 'alfred' {

         nginx::resource::vhost { 'puppet.com':
             ensure               => present,
             server_name          => [
    					'puppet.com',
    					'www.puppet.com'
    				],
             listen_port          => 80,
             www_root             => '/var/www/puppet',
             use_default_location => true,
             access_log           => '/var/log/nginx/puppet_access.log',
             error_log            => '/var/log/nginx/puppet_error.log',
         }

    }

And I get this error when I run the nginx module.

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[/var/opt/lib/pe-puppet/concat/_etc_nginx_sites-available_puppet.agileserver.com.conf/fragments/500_puppet.com-500-_] { notify => Exec[concat_/etc/nginx/sites-available/puppet.conf] }, because Exec[concat_/etc/nginx/sites-available/puppet.conf] doesn't seem to be in the catalog
    Warning: Not using cache on failed catalog
    Error: Could not retrieve catalog; skipping run

Any Thoughts?

**Comment by 3flex** [comment]
@blendimc sorry this waited so long for a reply... are you still experiencing this problem?

It might have been an issue with either this module or the puppetlabs/concat module, both of which have been updated since. I don't believe the config you show here would have any problems, but please reply if you still need assistance with this. We'd need your jfryman/nginx version number and puppetlabs/concat version number. Thanks!

**Comment by 3flex** [comment]
I'm closing this for now. @blendimc please comment if you have any information to add and I'll reopen. Thanks!
