### ISSUE TITLE
Circular dependency in 0.2.3

### ISSUE THREAD

**Issue by 3flex** [jfryman/puppet-nginx#609]
Copied from https://github.com/jfryman/puppet-nginx/issues/244#issuecomment-58404434

I am having the same problem (unrolled below for easier reading)...
```
err: Could not apply complete catalog: Found 1 dependency cycle:
( Anchor[nginx::end] 
  => Class[Nginx] 
  => Nginx::Resource::Vhost[vhost-searchhub] 
  => File[vhost-searchhub.conf symlink] 
  => Service[nginx]
  => Class[Nginx::Service] 
  => Anchor[nginx::end] )
```
Seems like nothing I do breaks this dependency cycle.

cc @shadone @bluecurio

**Comment by 3flex** [comment]
@shadone thanks for investigating the versions affected, it helped to narrow down the problem @bluecurio is having. On comparing 0.2.2 and 0.2.3 I see two changes to dependencies, one that shouldn't have any impact (https://github.com/jfryman/puppet-nginx/pull/557) and one that probably did (#553).

I'll need to investigate further and possibly untangle a few of the module's dependencies to simplify things and make it more robust.

**Comment by 3flex** [comment]
@shadone @bluecurio could you both please add your manifests, the Puppet version you're using, and confirm the module version you're using?

I've done a bit of investigation but I can't see anything that would be causing this behaviour.

**Comment by bluecurio** [comment]
Cheers Matt,

Unfortunately I can't provide a working case of the bug because my team
ended up using a the *passenger*
<https://github.com/phusion/passenger/wiki/Phusion-Passenger%3A-Node.js-tutorial>package
(which provides nginx) instead of using your module. I ultimately needed an
environment for my nodejs app to run and Passenger was easier than
rolling-my-own. Hope you understand. I've never used anchors (in Puppet),
so your guess is as good as mine as to what's going on in the nginx
module...

--Daniel



-Daniel

On Fri, Apr 17, 2015 at 12:21 AM, Matthew Haughton <notifications@github.com

**Comment by 3flex** [comment]
I'm closing this for now. @shadone please comment if you have any information to add and I'll reopen. Thanks!
