### ISSUE TITLE
Version inconsistencies ('v' prepended)

### ISSUE THREAD

**Issue by strarsis** [jfryman/puppet-nginx#801]
I am using librarian-puppet for pulling puppet-nginx.

With previous releases, including 0.2.7, it works with a version string without a 'v' prepended:
````
mod 'jfryman/puppet-nginx',
  :git => 'https://github.com/jfryman/puppet-nginx.git',
  :ref => '0.2.7'
````

Now for the latest release, 0.3.0, this doesn't work anymore:
````
mod 'jfryman/puppet-nginx',
  :git => 'https://github.com/jfryman/puppet-nginx.git',
  :ref => '0.3.0'
````
I get this error message for version string '0.3.0' without a 'v' prepended.
````
[...]
Could not checkout https://github.com/jfryman/puppet-nginx.git: fatal: ambiguous argument '0.3.0^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[...]
````

With a version string with 'v' prepended, it works again:
[...]
mod 'jfryman/puppet-nginx',
  :git => 'https://github.com/jfryman/puppet-nginx.git',
  :ref => 'v0.3.0'
[...]

This may be a bit nitpicky but I would really like to know the reason for this inconsistency.
And maybe it even indicates some smaller issue/typo with the git repository/puppet module metadata?

Thanks and 
with best regards

**Comment by 3flex** [comment]
The `:ref` is used to select a git commit, and you'd been using it to select a git tag in the past. It's not related to the version number used in the module metadata.

You should be able to use this in future to select the versions:

`mod 'jfryman-nginx', "0.3.0"`

This will pull it from the Puppet Forge instead of from Github.

Closing for now, please try this first then post again if you're still having issues. Thanks!
